name: Deploy app

on:
  push:
    branches:
      - master

jobs:
  build-staging:
    name: Build and Push Frontend Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the updated source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build image and push it to DockerHub
        uses: docker/build-push-action@v4
        with:
          build-args: NG_CONFIGURATION=staging
          push: true
          context: .
          tags: "smallhillcz/studentska-revolta:staging"
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to staging
    needs: build-staging
    runs-on: ubuntu-latest

    steps:
      - name: Tell the watchtower server there is a new image
        env:
          WATCHTOWER_URL: ${{ vars.WATCHTOWER_URL }}
          WATCHTOWER_TOKEN: ${{ secrets.WATCHTOWER_TOKEN }}
        run: 'curl -I -H "Authorization: Bearer $WATCHTOWER_TOKEN" $WATCHTOWER_URL'